---
deployment:
  tasks:
    - cd /home/avmultis/repositories/av-clinic
    - php composer.phar install --no-dev --optimize-autoloader
    - export DEPLOYPATH=/home/avmultis/public_html
    - /bin/cp -R public/* $DEPLOYPATH

    # Show the require line before editing
    - echo "Before sed:"
    - grep "require" $DEPLOYPATH/index.php

    # Modify require line
    - sed -i "s|require FCPATH\s*\.\s*'\.\./app/Config/Paths.php';|require __DIR__ . '/../repositories/av-clinic/app/Config/Paths.php';|" $DEPLOYPATH/index.php

    # Show the require line after editing
    - echo "After sed:"
    - grep "require" $DEPLOYPATH/index.php
