---
deployment:
  tasks:
    - export DEPLOYPATH=/home/avmultis/public_html/
    - echo "Copying images..." >> /home/avmultis/deploy.log
    - /bin/cp -R images $DEPLOYPATH >> /home/avmultis/deploy.log 2>&1
