---
deployment:
  tasks:
    - cd /home/avmultis/repositories/av-clinic
    - php composer.phar install --no-dev --optimize-autoloader
    - export DEPLOYPATH=/home/avmultis/public_html
    - /bin/cp -R public/* $DEPLOYPATH
